# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shelesh_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shelesh_Demo
	pod 'ReachabilitySwift'
	pod 'SDWebImage', '~> 5.0'
	pod 'SDWebImageSVGCoder'
end
